project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning"
  favicon: "static/favicon_32.png"
  search:
    type: textbox
  sidebar:
    background: primary
    logo: "static/ml_green.png"
    pinned: true
    align: center
    tools:
      - icon: house
        href: course_information/schedule.qmd
        text: Home
      - icon: file-earmark-pdf
        href: https://chefs-kiss.github.io/ML_J2026/files/ISLP.pdf
        text: ISLP
      - icon: chat-heart
        href: https://mdl.stolaf.edu/course/view.php?id=56310
        text: Moodle
      - icon: github
        href: https://github.com/chefs-kiss/ML_J2026
        text: GitHub
    style: docked
    contents:
    - href: index.qmd
      text: Home
    - href: course_information/schedule.qmd
      text: Schedule
    - href: content/00-INTRO.qmd
      text: Course Content
    - href: project.qmd
      text: Project
    - href: articles.qmd
      text: Article Reviews
    - href: content/06-OTHER.qmd
      text: Resources

format:
  html:
    theme: lux  #yeti #materia #lux #sandstone #spacelab #vapor   #litera
    #css: styles.css
    toc: true

execute:
  freeze: auto

