---
toc: false
---
Introduction to <br>
[Machine Learning]{style="font-family: 'Press Start 2P', monospace; font-size: 2.5em; color: #c668eb;"}

Machine learning algorithms are used to make decisions in a wide variety of applications, 
including recommendation systems, criminal justice, healthcare, and more. This course explores 
several common machine learning algorithms: how they work, their strengths and limitations, their 
applications to real-world datasets, their implementation via Python frameworks, and the ethical 
and societal consequences of their use.

--- 

## Staff 
Instructor: Prof. Kim Mandery<br>
Email: mander1@stolaf.edu<br>
Office: RMS 407<br>
Office Hours: M 12-2pm (virtual, [sign-up](https://calendar.app.google/Es7tf9wEG8h8N9Pw6)); T 2-3pm; W 10:20-12:30am, or by appt. <br>


## TA 
TA: Brooke Barenz<br>
TA Hours: TBD <br>
Drop-in lab: RNS202/203<br>


Additional help can often be found in the drop-in lab from Sunday-Thursdays around 6-9pm.

--- 

We will be using this site for most of our course content. Navigate to the schedule or course content using the wiki at the top of this page. You can read the syllabus [here](course_information/syllabus.qmd).

---
This site was made using [Quarto](https://quarto.org/docs/websites/)! If you are interested in building your own site to host your portfolio, reach out to Prof. Kim and she'll help you get started.
