

Note: Days that are bolded will be held asynchronously. 
Student will work through the material at their own pace, and schedule a time to meet with their lab partner (if needed).

## Week 1 (Jan 5 - 9)

| **dow** | **date**  | **prepare**       | **topic**              | **agenda**                                                                                   |
|:------:|:---------:|:-----------------|:----------------------|:------------------------------------------------------------------------------------------------|
| M       | Jan 5     | [📖<br><br> syllabus](syllabus.qmd){.badge .bg-light .text-decoration-none}     | INTRO                  |   [👩🏻‍🏫<br><br> INTRO](../slides.html?q=INTRO1){.badge .bg-light .text-decoration-none}  [☑️<br><br>PC0](../project.qmd#pc0){.badge .bg-light .text-decoration-none} 🍽️  [💻<br><br>Lab: Intro](../labs.qmd#lab-intro){.badge .bg-light .text-decoration-none}                   |
| T       | Jan 6     | [📖<br><br> readings](../01-EDA/rr-EDA.qmd){.badge .bg-light .text-decoration-none}     | [EDA](../01-EDA)                    |  [👩🏻‍🏫<br><br>EDA1](../slides.html?q=EDA1){.badge .bg-light .text-decoration-none} [👩🏻‍🏫<br><br>EDA2](../slides.html?q=EDA2){.badge .bg-light .text-decoration-none} 🍽️ [QUIZ <br><br>INTRO]{.badge .bg-info .text-decoration-none}  [📝<br><br>HW:EDA](/01-EDA/hw-EDA.qmd){.badge .bg-light .text-decoration-none}                 |
| W       | Jan 7     | [📓<br>EDA <br>standards](../01-EDA/std-EDA.qmd){.badge .bg-light .text-decoration-none}     | EDA                    |  [👩🏻‍🏫<br><br>EDA3](../slides.html?q=EDA3){.badge .bg-light .text-decoration-none} [☑️<br><br>PC1](../project.qmd#pc1){.badge .bg-light .text-decoration-none} 🍽️ [💻<br><br>Lab:EDA](../labs.qmd#lab-eda){.badge .bg-light .text-decoration-none} [😵‍💫 <br>TA help <br> 7:30-8:30]{.badge .bg-light .text-decoration-none}            |
| Th      | Jan 8     | [📖<br><br> readings](../02-EVL/rr-EVL.qmd){.badge .bg-light .text-decoration-none}     |  EVL      |  [👩🏻‍🏫<br><br>EVL1](../slides.html?q=EVL1){.badge .bg-light .text-decoration-none} [👩🏻‍🏫<br><br>EVL2](../slides.html?q=EVL2){.badge .bg-light .text-decoration-none} 🍽️ [QUIZ <br><br>EDA]{.badge .bg-info} [📝<br><br>HW:EVL](/02-EVL/hw-EVL.qmd){.badge .bg-light .text-decoration-none}                |
| F       | **Jan 9**     | [📓<br>EVL<br> standards](../02-EVL/std-EVL.qmd){.badge .bg-light .text-decoration-none}      |  EVL                    | [👩🏻‍🏫<br><br>EVL3](../slides.html?q=EVL3){.badge .bg-light .text-decoration-none}  [☑️<br><br>PC2](../project.qmd#pc2){.badge .bg-light .text-decoration-none} [💻<br><br>Lab:EVL](../labs.qmd#lab-evl){.badge .bg-light .text-decoration-none} [😵‍💫 <br>TA help <br> 2:00-3:00]{.badge .bg-light .text-decoration-none}                                                |
| Su      | Jan 11    | | |[📰 <br> article <br> review](../articles.qmd){.badge .bg-light .text-decoration-none}  [😵‍💫 <br>TA help <br> 8:00-9:00]{.badge .bg-light .text-decoration-none}

## Week 2 (Jan 12 - 16)

| **dow** | **date**  | **prepare**       | **topic**              | **agenda**                                                                                   |
|:------:|:---------:|:-----------------|:----------------------|:------------------------------------------------------------------------------------------------|
| M       | Jan 12    | [📖<br><br> readings](../03-CLS/rr-CLS.qmd){.badge .bg-light .text-decoration-none}      |  CLS      | [👩🏻‍🏫<br><br>CLS1](../slides.html?q=CLS1){.badge .bg-light .text-decoration-none} [👩🏻‍🏫<br><br>CLS3](../slides.html?q=CLS1){.badge .bg-light .text-decoration-none}  [📝<br><br>HW:CLS](/03-CLS/hw-CLS.qmd){.badge .bg-light .text-decoration-none} 🍽️ [QUIZ <br><br>EVL]{.badge .bg-info}     |
| T       | Jan 13    | [📓<br>CLS<br> standards](../03-CLS/std-CLS.qmd){.badge .bg-light .text-decoration-none}     | CLS   |  [👩🏻‍🏫<br><br>CLS3](../slides.html?q=CLS3){.badge .bg-light .text-decoration-none} [☑️<br><br>PC3](../project.qmd#pc3){.badge .bg-light .text-decoration-none} 🍽️ [💻<br><br>Lab:CLS](../labs.qmd#lab-cls){.badge .bg-light .text-decoration-none}  [QUIZ <br> RETAKES <br> EDA + EVL]{.badge .bg-info .text-decoration-none} [😵‍💫 <br>TA help <br> 7:00-8:00]{.badge .bg-light .text-decoration-none}                        |
| W       | Jan 14    | [📖<br><br> readings](../04-DATA/rr-DATA.qmd){.badge .bg-light .text-decoration-none}      |  DATA     |  [👩🏻‍🏫<br><br>DATA1](../slides.html?q=DATA1){.badge .bg-light .text-decoration-none}  [👩🏻‍🏫<br><br>DATA2](../slides.html?q=DATA2){.badge .bg-light .text-decoration-none}  [📝<br><br>HW:DATA](../04-DATA/hw-DATA.qmd){.badge .bg-light .text-decoration-none} 🍽️ [Worktime: <br> PC or Lab]{.badge .bg-light .text-decoration-none}              |
| Th      | Jan 15    | [📓<br>DATA<br> standards](../04-DATA/std-DATA.qmd){.badge .bg-light .text-decoration-none}   | DATA                   |    [💻<br><br>Lab:DATA](../labs.qmd#lab-data){.badge .bg-light .text-decoration-none}🍽️[👩🏻‍🏫<br><br>TREE1](../slides.html?q=TREE1){.badge .bg-light .text-decoration-none} [TREE<br><br>WS](../05-TREE/WS-TREE.qmd){.badge .bg-light .text-decoration-none} [QUIZ <br><br>CLS]{.badge .bg-info}  [😵‍💫 <br>TA help <br> 7:00-8:00]{.badge .bg-light .text-decoration-none}               |
| F       | Jan 16    | [📖<br><br> readings](../05-TREE/rr-TREE.qmd){.badge .bg-light .text-decoration-none}    |  TREE     |  [👩🏻‍🏫<br><br>TREE2](../slides.html?q=TREE2){.badge .bg-light .text-decoration-none} [👩🏻‍🏫<br><br>TREE3](../slides.html?q=TREE3){.badge .bg-light .text-decoration-none} [📝<br><br>HW:TREE](../05-TREE/hw-TREE.qmd){.badge .bg-light .text-decoration-none}  🍽️ [QUIZ <br><br>DATA]{.badge .bg-info}  [☑️<br><br>PC4](../project.qmd#pc4){.badge .bg-light .text-decoration-none}                   |

<!-- move quiz retakes EDA/EVL from Tu to W afternoon  -->

## Week 3 (Jan 19 - 23)

| **dow** | **date**  | **prepare**       | **topic**              | **agenda**                                                                                   |
|:------:|:---------:|:-----------------|:----------------------|:------------------------------------------------------------------------------------------------|
| M       | **Jan 19**    |   | No Class   |    [☑️<br><br>PC5](../project.qmd#pc5){.badge .bg-light .text-decoration-none}    | 
| T       | Jan 20    |  [📓<br>TREE<br> standards](../05-TREE/std-TREE.qmd){.badge .bg-light .text-decoration-none}   |  TREE     | [👩🏻‍🏫<br><br>LIN1](../slides.html?q=LIN1){.badge .bg-light .text-decoration-none}  [👩🏻‍🏫<br><br>LIN2](../slides.html?q=LIN2){.badge .bg-light .text-decoration-none} [📝<br><br>HW:LIN](../06-LIN/hw-LIN.qmd){.badge .bg-light .text-decoration-none}  🍽️[💻<br><br>Lab:TREE](../labs.qmd#lab-tree){.badge .bg-light .text-decoration-none}    [😵‍💫 <br>TA help <br> 7:00-8:00]{.badge .bg-light .text-decoration-none}         |
| W       | Jan 21    |   [📖<br><br> readings](../08-ESB/rr-ESB.qmd){.badge .bg-light .text-decoration-none}  | MOD                    | [👩🏻‍🏫<br><br>KNN](../slides.html?q=KNN){.badge .bg-light .text-decoration-none}[👩🏻‍🏫<br><br>SVM](../slides.html?q=SVM){.badge .bg-light .text-decoration-none}  🍽️ [QUIZ <br><br>TREE]{.badge .bg-info}  [QUIZ <br> RETAKES <br>  CLS + DATA]{.badge .bg-info .text-decoration-none}  |
| Th      | Jan 22    |      |   ESB      |  [👩🏻‍🏫<br><br>ESB1](../slides.html?q=ESB1){.badge .bg-light .text-decoration-none} [👩🏻‍🏫<br><br>ESB2](../slides.html?q=ESB1){.badge .bg-light .text-decoration-none}   [📝<br><br>HW:ENS](../08-ESB/hw-ESB.qmd){.badge .bg-light .text-decoration-none}  🍽️ [QUIZ <br><br>LIN]{.badge .bg-info}[☑️<br><br>PC6](../project.qmd#pc6){.badge .bg-light .text-decoration-none}                      |
| F       | **Jan 23**    |     [📓<br>LIN<br> standards](../06-LIN/std-LIN.qmd){.badge .bg-light .text-decoration-none}             | ESB   |  [💻<br>Lab:MOD <br> Part 1](../labs.qmd#lab-models){.badge .bg-light .text-decoration-none}         |

Over the weekend, complete an [article review](../articles.qmd)

## Week 4 (Jan 26 - 30)

| **dow** | **date**  | **prepare**       | **topic**              | **agenda**                                                                                   |
|:------:|:---------:|:-----------------|:----------------------|:------------------------------------------------------------------------------------------------|
| M       | Jan 26    |      |  ESB       |[👩🏻‍🏫<br><br>ESB3](../slides.html?q=ESB3){.badge .bg-light .text-decoration-none} [MOD<br><br>WS](../07-MOD/WS-MOD.qmd){.badge .bg-light .text-decoration-none} [☑️<br><br>PC7](../project.qmd#pc7){.badge .bg-light .text-decoration-none} [☑️<br><br>PC8](../project.qmd#pc8){.badge .bg-light .text-decoration-none} 🍽️ [💻<br>Lab:MOD <br>Part 2](../labs.qmd#lab-models){.badge .bg-light .text-decoration-none}                       |
| T       | Jan 27    |    [📓<br>ESB<br> standards](../08-ESB/std-ESB.qmd){.badge .bg-light .text-decoration-none}   | NN                                |    [👩🏻‍🏫<br><br>NN1](../slides.html?q=NN1){.badge .bg-light .text-decoration-none}  [👩🏻‍🏫<br><br>NN2](../slides.html?q=NN2){.badge .bg-light .text-decoration-none}[📝<br><br> HW:NN](../09-NN/hw-NN.qmd){.badge .bg-light .text-decoration-none} 🍽️ [QUIZ <br><br>ENS]{.badge .bg-info} [☑️<br>work<br>time](../project.qmd#pc6){.badge .bg-light .text-decoration-none}                                |
| W       | Jan 28    | [📖<br><br> readings](){.badge .bg-light .text-decoration-none} [📓<br>NN<br> standards](../09-NN/std-NN.qmd){.badge .bg-light .text-decoration-none} |  NN        | [👩🏻‍🏫<br><br>NN3](../slides.html?q=NN3){.badge .bg-light .text-decoration-none} [☑️<br><br>PC9](){.badge .bg-light .text-decoration-none}🍽️  [👩🏻‍🏫<br><br>STORY](../slides.html?q=STORY){.badge .bg-light .text-decoration-none}[😵‍💫 <br>TA help <br> 7:00-8:00]{.badge .bg-light .text-decoration-none}                                          |
| Th      | Jan 29    |     | Final Day    | [QUIZ <br>(group)<br>NN]{.badge .bg-info}  [QUIZ <br> RETAKES <br>  ANY]{.badge .bg-info .text-decoration-none} 🍽️ [☑️<br><br>PREZ](../project.qmd#presentations){.badge .bg-light .text-decoration-none}                           |
| F       | **Jan 30**    |     [submit<br>presentation](){.badge .bg-light .text-decoration-none}             | No Class  |                                                                                  |

